title: 'Community Mediation Centre'
description: Description
url: 'https://cmc.mlaw.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
resources_name: press-room
favicon: /images/favicon-cmc.ico
google_analytics: UA-10405444-21
permalink: none
baseurl: ""
defaults:
  -
    scope:
      path: ""
    values:
      layout: page
staging: https://mlaw-cmc-staging.netlify.app
prod: https://mlaw-cmc-prod.netlify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
