title: 'Community Mediation Centre'
description: Description
url: 'https://cmc.mlaw.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
collections:
    self-manage-conflicts:
        output: true
    publications:
        output: true
    press-room:
        output: true
    partner-with-us:
        output: true
    e-services:
        output: true
    apply-for-mediation:
        output: true
    about-us:
        output: true
resources_name: press-room
favicon: /images/favicon-cmc.ico
google-analytics: UA-10405444-21
permalink: none
baseurl: ""
defaults:
    -
        scope:
            path: ""
        values:
            layout: page
