title: Community Mediation Centre
description: Description
url: https://cmc.mlaw.gov.sg
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
resources_name: press-room
favicon: /images/favicon-cmc.ico
google_analytics: UA-10405444-21
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
staging: https://staging.d2rtd0d1569qhg.amplifyapp.com/
prod: https://master.d2rtd0d1569qhg.amplifyapp.com/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
colors:
  primary-color: "#4f709c"
  secondary-color: "#4f709c"
  media-colors:
    - title: media-color-one
      color: "#d8c4b6"
    - title: media-color-two
      color: "#f5efe7"
    - title: media-color-three
      color: "#213555"
    - title: media-color-four
      color: "#d8c4b6"
    - title: media-color-five
      color: "#d8c4b6"
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
